In [13]:
import numpy as np

In [75]:
np.vander([1,2,3])#vandeermone inbuilt function

array([[1, 1, 1],
       [4, 2, 1],
       [9, 3, 1]])

# 1

In [76]:
def vandermonde(Vector, N, increasing = False):
    if increasing:
        Matrix = np.matrix([x**i for x in Vector for i in range(N)]).reshape(Vector.size, N)
    else:
        Matrix = np.matrix([x**(N-i-1) for x in Vector for i in range(N)]).reshape(Vector.size, N)
    return Matrix

In [77]:
Vector = np.array([1, 3, 5, 7, 9])
N = 5

In [78]:
Mtarix_desc = vandermonde(Vector, N, False)
Mtarix_desc

matrix([[   1,    1,    1,    1,    1],
        [  81,   27,    9,    3,    1],
        [ 625,  125,   25,    5,    1],
        [2401,  343,   49,    7,    1],
        [6561,  729,   81,    9,    1]])

In [79]:
Mtarix_asc = vandermonde(Vector, N, True)
Mtarix_asc

matrix([[   1,    1,    1,    1,    1],
        [   1,    3,    9,   27,   81],
        [   1,    5,   25,  125,  625],
        [   1,    7,   49,  343, 2401],
        [   1,    9,   81,  729, 6561]])

# 2

In [101]:
def moving_Average(inputValue, c):
    v = 1
    output = np.convolve(inputValue, np.ones(c), 'valid') / c
    for i in output:
        print("y{0} = {1:.2f}".format(v, i))
        v += 1

In [102]:
inputValue = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
c = 3
moving_Average(inputValue, c)

y1 = 5.00
y2 = 4.67
y3 = 5.67
y4 = 6.67
y5 = 9.67
y6 = 28.67
y7 = 49.33
y8 = 72.67
y9 = 84.00
y10 = 93.33
y11 = 116.33
